
// Frame
#define FRAME_GLOBAL 0
#define FRAME_LOCAL_NED 1
#define FRAME_MISSION 2
#define FRAME_GLOBAL_REL_ALT 3
#define FRAME_LOCAL_ENU 4

// NAV cmd
#define NAV_WAYPOINT 16
#define NAV_LOITER_UNLIM 17
#define NAV_LOITER_TURNS 18
#define NAV_LOITER_TIME 19
#define NAV_RETURN_TO_LAUNCH 20
#define NAV_LAND 21
#define NAV_TAKEOFF 22
